---
- name: No‑Op Metrics Collection Playbook
  hosts: all
  gather_facts: false

  roles:
    - dummy_role
    - metrics_role

  tasks:
    - name: Gather minimal facts (setup module)
      ansible.builtin.setup:
        gather_subset: "!all"
      changed_when: false

    - name: Ping back (ping module)
      ansible.builtin.ping:
      register: ping_result

    - name: Debug ping result
      ansible.builtin.debug:
        var: ping_result

    - name: Debug completion message (debug module)
      ansible.builtin.debug:
        msg: "No‑op task completed – for metrics only"
